source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RTSMTableSectionManager_Example', :exclusive => true do
  pod 'RTSMTableSectionManager', :path => '../'
  pod 'ResplendentUtilities', '0.3.2'
end

target 'RTSMTableSectionManager_Tests', :exclusive => true do
  pod 'RTSMTableSectionManager', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
