platform :ios, '7.0'

use_frameworks!

target 'RTSMTableSectionManager_Example' do
  pod 'RTSMTableSectionManager', :path => '../'

  target 'RTSMTableSectionManager_Tests' do
    inherit! :search_paths
  end
end
